### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by leifclaesson** [Christian-Me/node-red-contrib-homie-convention#11]
Hi! I'm brand new to Node-RED but an otherwise experienced C++ developer, in fact I have written my own [Homie library](https://github.com/leifclaesson/LeifHomieLib) for ESP8266/ESP32.

I wasn't sure how to contact you so I'm creating this issue. You can e-mail me back at github@leif.lc for more direct communication if you like.

I have just started using Node-RED for home automation (seems like a less labor-intensive choice than C++) and came across this library, but I've come across several issues already. Part of it may be user error, other things may be architectural, but I figured I'd contact you and ask.

### Undefined datatype?
When connected to my existing MQTT broker with lots of my own homie devices, in the status line of the node, different updates are constantly being reflected. Most seem to work, but many display as **$datatype undefined or invalid: undefined**
I don't know how to debug that -- as far as I know I am only using defined data types, and openhab is happy with them. Is there debug output? How do I find out what it is your homie device node is not happy about?

### Node dropdown does not populate
None of my homie devices nodes show up in the Node dropdown, except for $stats. I don't know why. The topics are there and openhab sees them.

I also had some questions about the Homie node node, but as I was writing the explanation of the problem, I think I suddenly understood how you intended for it to be used, so I'm going to try that rather than bothering you with it. :)

Thanks in advance.
Best regards,
Leif Claesson

**Comment by Christian-Me** [comment]
Hi Leif,

Communication here is fine as sometimes others can participate. 

I think you are refereeing to the current npm / master version. In fact I'm redesigning the complete suite of nodes. These are currently in beta and can be accessed in then development branch. 

I highly recommend to uses this and will be more than happy to address every bug. [a little preview here](https://discourse.nodered.org/t/announce-node-red-contrib-homie-convention/16329/34?u=christian-me)

First I expect that the messages  are stored on your broker as retained. The mqtt standard is quite vague in this respect. The best way is to send messages as QOS>0 and the retained flag or convince your broker to store QoS = 0 messages  too.

The validation process is now completely redone and should work better (at least with my suite of devices). I use either ESPEasy (with the com plugin i wrote some years ago) but nowadays I develop my own firmware as you do .  

All the UI stuff is now in a sperate node. Not reworked in all parts but some are working. I will take a look at the dropdown feature. Many components and APIs of the dashboard changed over the years. The slider and switch part are already fixed as I needed them for my own projects : min / max value, disable the widget if /set value is not confirmed and $state!=ready will disable the widget

the homie node node is called now "homie pro" (still not a good name) with a new concept. 

Please understand that don't have the time to maintain 2 versions.

Happy to collaborate to get this working properly.

Chris
