### ISSUE TITLE
node id not shown in node dropdown

### ISSUE THREAD

**Issue by wurststulle** [Christian-Me/node-red-contrib-homie-convention#2]
hey, i am trying this module with config based on the example from homieiot.github.io. it seems, as the node is not parsed correctly, or i am using it wrong. maybe someone can give some advice whats wrong here.
`mosquitto_pub -h 192.168.x.x -t "homie/switch-controller/$homie" -m "4.0"
mosquitto_pub -h 192.168.x.x -t "homie/switch-controller/$name" -m "SwitchController"
mosquitto_pub -h 192.168.x.x -t "homie/switch-controller/$nodes" -m "switch-sensor"
mosquitto_pub -h 192.168.x.x -t "homie/switch-controller/$state" -m "ready"

mosquitto_pub -h 192.168.x.x -t "homie/switch-controller/switch-sensor/$name" -m "SwitchSensor1"
mosquitto_pub -h 192.168.x.x -t "homie/switch-controller/switch-sensor/$properties" -m "sw0"

mosquitto_pub -h 192.168.x.x -t "homie/switch-controller/switch-sensor/sw0" -m "off"
mosquitto_pub -h 192.168.x.x -t "homie/switch-controller/switch-sensor/sw0/$name" -m "state"
mosquitto_pub -h 192.168.x.x -t "homie/switch-controller/switch-sensor/sw0/$datatype" -m "enum"
mosquitto_pub -h 192.168.x.x -t "homie/switch-controller/switch-sensor/sw0/$format" -m "on,off"` 

the node _switch-sensor_ is not shown in node dropdown.

**Comment by Christian-Me** [comment]
Hi,
I see (only one )problem.

- 1st and most important the messages have to be send as retained messages. see here [QoS and retained messages](https://homieiot.github.io/specification/#qos-and-retained-messages)
- if you are using a small micro and unable to send your messages with QoS=2 or 1 (i.e. if you are using the pubsub library) you can configure mosquitto to accept and store retained messages [see here](https://github.com/Christian-Me/node-red-contrib-home/tree/master/Mosquitto). In default configuration mosquitto retaines messages sent QoS=0 messages but do not save them.
- For testing use -q 2 -r 
- $type is not specified (see 5.2.1 of the convention)

![image](https://user-images.githubusercontent.com/15779507/69912019-36439b80-1424-11ea-9789-50c5a5d952af.png)

**Comment by wurststulle** [comment]
works as expected, thanks for the clarification.

**Comment by Christian-Me** [comment]
Good to hear that it’s working. Have to write a clarification on this topic as it is a fundamental mechanism for homie to work. One of the big strength of homie is using mqtt retained messages  as build in persistence ability - but not clearly explained, especially the implementation in mqtt in relation to qos and limitations of some libraries for microcontrollers.
