### ISSUE TITLE
Username/Password don´t save on broker config form

### ISSUE THREAD

**Issue by filipemateus** [Christian-Me/node-red-contrib-homie-convention#3]
Hey,

Username/Password data on broker config form don´t apply. I Fulfil it and saved but when I close the form and do deploy these data are lost.

**Comment by Christian-Me** [comment]
Hello,
That has something to do that username and password are stored encrypted in the credentials file. The front end does not get the username easily, The password will not be sent back to the front end at all. 
But the node should have received username / password and connect correctly:
 
![image](https://user-images.githubusercontent.com/15779507/70369571-1137a880-18bc-11ea-9421-e0c6f0b2d047.png)

![image](https://user-images.githubusercontent.com/15779507/70369611-8b682d00-18bc-11ea-89d7-9d5bc61bdfb7.png)

I have to find the right way to react on the front end: I use a password manager so the data is filled in every time I open the broker config dialog.
Can you establish a username/password connection after typing in the values and deploy/restart flow partial deploy sometimes not trigger a re-connection of the mqtt client.

**Comment by Christian-Me** [comment]
Ok, found the problem. can you install the node from github for a test before I push it to npm?
![image](https://user-images.githubusercontent.com/15779507/70371016-ca52ae80-18cd-11ea-9cc3-9a1a6e5129a8.png)

**Comment by filipemateus** [comment]
Hello Christian,

I did install from Github and the problem remains.

I´m using Docker to setup this env. I´m using RabbitMQ too linked to NodeRED container. I´m not using TLS, only user/pass

![Screen Shot 2019-12-07 at 10 43 09](https://user-images.githubusercontent.com/5713202/70375638-c418fe00-18de-11ea-8886-8cf32ad4e9c9.png)

**Comment by Christian-Me** [comment]
Can you take a look inside the log / console? you should read something like this

```
7 Dec 15:18:39 - [info] Flows starten
7 Dec 15:18:39 - [info] [homie.device.config:mosquitto@home] MQTT connect to mqtt://192.168.2.14:1883 as user undefined
7 Dec 15:18:39 - [info] [homie.device.config:localhost@hp-spectre-360] MQTT connect to mqtts://AH-BERLIN-0148:8883 as user mqttUser
```
Search for someting starting with `homie.device.config`
Currently i have two brokers. one on my server (without tsl and without user/pass and secont with tsl&user. I don`t think it has something to do with docker or your broker,

**Comment by filipemateus** [comment]
Sure

![Screen Shot 2019-12-07 at 21 16 39](https://user-images.githubusercontent.com/5713202/70382211-0110df00-1937-11ea-9a3b-982dcadd4d42.png)

Apparently, for some unknown reason NodeRED don´t store  the data :(

**Comment by filipemateus** [comment]
Hi Christian, 

I´d wrong my setup of homie via GitHub on Node-red. Now is connecting \o/

![Screen Shot 2019-12-07 at 22 39 11](https://user-images.githubusercontent.com/5713202/70382885-6ddda680-1942-11ea-9ffb-6c453c394a5e.png)

Thanks so much for the aid. Best regards

**Comment by Christian-Me** [comment]
Just wanted to write that it seems that you still have the old version.... Great that it is working now. Come back if you encounter any further problems / bugs The is a lonely post over @ forum too for non bug related discussion. The note is quite complex and I real need help with beta testing. I'll push 0.5 to npm  ASAP (on Monday because if have guests today)

![image](https://user-images.githubusercontent.com/15779507/70386705-3bf92e00-199c-11ea-8037-9299ea0533b2.png)

Greetings from Berlin
