### ISSUE TITLE
Properties not shown in dropdown 

### ISSUE THREAD

**Issue by nische** [Christian-Me/node-red-contrib-homie-convention#8]
Hi, 
at the moment i dev a node that convert the Homematic mqtt output/input to Homie MQTT. 
To check my implementation i use the homie-convention nodes.  In my fist trys i get the properties showen (testet only two seperated by ",") after i add all posible properties the dropdown etc. stopt working. 

![MQTT-Explorer](https://user-images.githubusercontent.com/42242845/103559306-367b5980-4eb6-11eb-8f6e-e612dc51a1bf.png)

![My Testflow](https://user-images.githubusercontent.com/42242845/103559435-69255200-4eb6-11eb-8ada-42ef629d8122.png)

![Dropdown](https://user-images.githubusercontent.com/42242845/103559543-95d96980-4eb6-11eb-83c4-dfea16a55766.png)

Is it possible, that you only show the properties, if you get a msg for every property in the $properties element? 

BR, Nico

**Comment by Christian-Me** [comment]
Hi Nico, Happy New Year!

Nice to see that someone actually using this node;) 

1st Are your sure that your homie structure is correct?
![image](https://user-images.githubusercontent.com/15779507/103645172-dd640200-4f57-11eb-8f7f-455bd3389f4a.png)

Seems to me that there is a bit of a mismatch.
2nd you can inspect the date the Homie node collected in the global store. I normally take a look there.
3rd Please make sure that your messages are `retained`.  I usually check this by

- let your system send out all data
- stop node red or any other device updating your broker data
- restart mqtt explorer.
- all your retained data should pop up after restart and flagged as retained.

(Hint: messages with the retained flag set but received "live/online" are not flagged as retained!)

I actually work on a complete rework of the homie node showing the homie data in a tree list .... but not enough time to finish the fine tuning and beta testing ...

**Comment by Christian-Me** [comment]
BTW here is my solution ... ( the red branch is the homematic to homie converter)
![image](https://user-images.githubusercontent.com/15779507/103647156-1fdb0e00-4f5b-11eb-92a1-39b8dd191213.png)
The homie to homematic flow is still not even started

**Comment by nische** [comment]
oh yes :D a Happy New Year too. Because of the Lockdown in Germany i lost the turn of the year :D and thanks for the fast reply.

At the moment I rework my smarthome to fully HomieMQTT to increase my opportunities. (Everything is better with a "standard" :D)

1. i interpreted the $name as an better readable name for the topic not the Topic it self. 
![image](https://user-images.githubusercontent.com/42242845/103666785-5cb3fe80-4f75-11eb-8cf5-4cd2e37eec44.png)

2. Sry i overlooked this feature
3. The Messages are retained (im very sure because i have trouble with old messages/topics yesterday).


But it is correct that you not need a message with the attributes for every property on start? 

Thanks for your Solution but I dont  do this struct/interpretation for every new HM Component. In the payload from the Homematic MQTT node are a lot of informations about the data, so that the biggest part of the interpretation can be automated. Only a few (but necessary) data are productspezific.

**Comment by Christian-Me** [comment]
Hi back.
My point was that the $name topic reads cannel1 and deviceId ch1 but you selected channel2 in the dropdown - are you sure that there are properties defined as in channel2?
If you look into the global store (data tab) you should be able to inspect the acquired homie data inside the editor.
 

The (old) node is not very error tolerant. So perhaps correct the $properties topic that there are only existing properties listed.

> But it is correct that you not need a message with the attributes for every property on start?

Don't know what you ask here. Which node?

**Comment by Christian-Me** [comment]
Perhaps this could help you too 
https://github.com/Christian-Me/remote-device-table

**Comment by nische** [comment]
Hi again, 
i switch my project "republisher" from a subflow to my own node and send all properties on startup. This fixed my "issue". 

btw. your remote-device-table is nice :)

**Comment by Christian-Me** [comment]
Good to hear that it is now working as expected.

This is the latest "beta" of the complete rework of the homie nodes

support for multiple base ids (autodetect)
cherry picking of individual properties, support for extensions and many more features
If you like to beta check I can push it to github. 

![image](https://user-images.githubusercontent.com/15779507/104741018-ef5c5680-5748-11eb-9081-d5a91cfa951e.png)
